name: ci-cd demo
on:
  push:
    branches:
      - main
jobs:
    test:
        name: "Tste Code"
        runs-on: ubuntu-latest
        steps:
            - name: get-Code
              uses: actions/checkout@v4
            - name: check file
              run: |
                echo "check file..."
                test -f index.html && echo "HTML found"
                test -f styles.css && echo "style found"
                echo "All files ok"

    build:
        name: build & deploy
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v4
            - name: build
              run: |
                echo "build image"
                docker build -t ci-cd-demo .
                


